/*
 *    MCreator note:
 *
 *    This file is autogenerated to connect all MCreator mod elements together.
 *
 */
package net.mugmansnarutomod;

import net.minecraftforge.forgespi.language.ModFileScanData;
import net.minecraftforge.fml.network.NetworkEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.api.distmarker.OnlyIn;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.biome.Biome;
import net.minecraft.util.ResourceLocation;
import net.minecraft.tags.Tag;
import net.minecraft.network.PacketBuffer;
import net.minecraft.item.Item;
import net.minecraft.entity.EntityType;
import net.minecraft.enchantment.Enchantment;
import net.minecraft.block.Block;

import java.util.function.Supplier;
import java.util.function.Function;
import java.util.function.BiConsumer;
import java.util.Set;
import java.util.Map;
import java.util.List;
import java.util.HashMap;
import java.util.Collections;
import java.util.ArrayList;

import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Retention;

public class MugmansnarutomodModElements {
	public final List<ModElement> elements = new ArrayList<>();
	public final List<Supplier<Block>> blocks = new ArrayList<>();
	public final List<Supplier<Item>> items = new ArrayList<>();
	public final List<Supplier<Biome>> biomes = new ArrayList<>();
	public final List<Supplier<EntityType<?>>> entities = new ArrayList<>();
	public final List<Supplier<Enchantment>> enchantments = new ArrayList<>();
	public static Map<ResourceLocation, net.minecraft.util.SoundEvent> sounds = new HashMap<>();
	public MugmansnarutomodModElements() {
		sounds.put(new ResourceLocation("mugmansnarutomod", "sexiness"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "sexiness")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "confrontment"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "confrontment")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "ninetaileddemonfox"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "ninetaileddemonfox")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "acrisisafteranother"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "acrisisafteranother")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "sasukestheme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "sasukestheme")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "nervous"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "nervous")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "survivalexamination"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "survivalexamination")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "afternoonofkonoha"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "afternoonofkonoha")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "foolingmode"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "foolingmode")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "sadnessandsorrow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "sadnessandsorrow")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "avenger"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "avenger")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "itsthetraining"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "itsthetraining")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "gaistheme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "gaistheme")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "heavyviolence"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "heavyviolence")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "kakashistheme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "kakashistheme")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "orochimarustheme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "orochimarustheme")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "griefandsorrow"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "griefandsorrow")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "orochimarusfight"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "orochimarusfight")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "raikiri"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "raikiri")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "bunta"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "bunta")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "strongandstrike"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "strongandstrike")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "narutomaintheme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "narutomaintheme")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "isaidimnaruto"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "isaidimnaruto")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "rockleestheme"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "rockleestheme")));
		sounds.put(new ResourceLocation("mugmansnarutomod", "orochiquaza"),
				new net.minecraft.util.SoundEvent(new ResourceLocation("mugmansnarutomod", "orochiquaza")));
		try {
			ModFileScanData modFileInfo = ModList.get().getModFileById("mugmansnarutomod").getFile().getScanResult();
			Set<ModFileScanData.AnnotationData> annotations = modFileInfo.getAnnotations();
			for (ModFileScanData.AnnotationData annotationData : annotations) {
				if (annotationData.getAnnotationType().getClassName().equals(ModElement.Tag.class.getName())) {
					Class<?> clazz = Class.forName(annotationData.getClassType().getClassName());
					if (clazz.getSuperclass() == MugmansnarutomodModElements.ModElement.class)
						elements.add((MugmansnarutomodModElements.ModElement) clazz.getConstructor(this.getClass()).newInstance(this));
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
		Collections.sort(elements);
		elements.forEach(MugmansnarutomodModElements.ModElement::initElements);
	}

	public void registerSounds(RegistryEvent.Register<net.minecraft.util.SoundEvent> event) {
		for (Map.Entry<ResourceLocation, net.minecraft.util.SoundEvent> sound : sounds.entrySet())
			event.getRegistry().register(sound.getValue().setRegistryName(sound.getKey()));
	}
	private int messageID = 0;
	public <T> void addNetworkMessage(Class<T> messageType, BiConsumer<T, PacketBuffer> encoder, Function<PacketBuffer, T> decoder,
			BiConsumer<T, Supplier<NetworkEvent.Context>> messageConsumer) {
		MugmansnarutomodMod.PACKET_HANDLER.registerMessage(messageID, messageType, encoder, decoder, messageConsumer);
		messageID++;
	}

	public List<ModElement> getElements() {
		return elements;
	}

	public List<Supplier<Block>> getBlocks() {
		return blocks;
	}

	public List<Supplier<Item>> getItems() {
		return items;
	}

	public List<Supplier<Biome>> getBiomes() {
		return biomes;
	}

	public List<Supplier<EntityType<?>>> getEntities() {
		return entities;
	}

	public List<Supplier<Enchantment>> getEnchantments() {
		return enchantments;
	}
	public static class ModElement implements Comparable<ModElement> {
		@Retention(RetentionPolicy.RUNTIME)
		public @interface Tag {
		}
		protected final MugmansnarutomodModElements elements;
		protected final int sortid;
		public ModElement(MugmansnarutomodModElements elements, int sortid) {
			this.elements = elements;
			this.sortid = sortid;
		}

		public void initElements() {
		}

		public void init(FMLCommonSetupEvent event) {
		}

		public void serverLoad(FMLServerStartingEvent event) {
		}

		@OnlyIn(Dist.CLIENT)
		public void clientLoad(FMLClientSetupEvent event) {
		}

		@Override
		public int compareTo(ModElement other) {
			return this.sortid - other.sortid;
		}
	}
}
